### ISSUE TITLE
postprocessing.db cannot be found if path contains symbolic links

### ISSUE THREAD

**Issue by schmandr** [sogis/nplso_veriso#1]
postprocessing.db cannot be found if path contains symbolic links. In the following line, use `os.path.abspath(...)` instead:
https://github.com/sogis/nplso_veriso/blob/7763db8e6d2db353448003301a6305529e7ae6df/base/file/importproject.py#L679

**Comment by barpastu** [comment]
Fixed in 5396d17ca6b5f8057fa9f530548fa8e4d86d4cf8
